<?php
/**
* Put all you custom functions here
*/

function datetime_to_text($datetime = "", $show_time = true)
{
	$unixdatetime = strtotime($datetime);
	if ($show_time) {
		$time = strftime("%B %d, %Y at %I:%M %p", $unixdatetime);
	} else {
		$time = strftime("%B %d, %Y", $unixdatetime);
	}
	return $time;
}
function datetime_unix_to_text($datetime = "")
{
	return strftime("%d-%m-%y %I:%M:%S", $datetime);
}
function datetime_to_text_only($datetime = "")
{
	$unixdatetime = strtotime($datetime);
	return strftime("%B %d, %Y", $unixdatetime);
}

function ebika()
{
	return ["Abalangira","Babiito-Kooki","Babiito-Kiziba","Babiito-Kibulala","Butiko","Ffumbe","Kasimba","Kayozi","Kibe","Kinyomo","Kiwere","Kkobe","Lugave","Mazzi ga Kisasi","Mbogo","Mbwa","Mmamba","Mpeewo","Mpindi","Mpologoma","Musu","Mutima","Nakinsige","Ndiga","Ndiisa","Ngabi","Ng'aali","Ngeye","Ngo","Ngonge","Njaza","Njobe","Njovu","Nkejje","Nkerebwe","Nkima","Nkula","Nnamung'oona","Nnyonyi Nnyange","Nseenene","Nsuma","Nswaswa","Ntalaganya","Nte","Nvubu","Nvuma","Kasanke","Kibuba","Lukato","Mbuzi","Nkebuka","Nsunu"];

}

//$kabbiro = ebika2()[$_REQUEST['omuziro']];

function ebika2()
{
	return [
		"Abalangira"=>"",
		"Babiito-Kooki"=>"Mazzi ga Kisasi",
		"Babiito-Kiziba"=>"",
		"Babiito-Kibulala"=>"",
		"Butiko"=>"Namulondo",
		"Ffumbe"=>"Kikere",
		"Kasimba"=>"Ngo",
		"Kayozi"=>"Nsombabyuma",
		"Kibe"=>"Kassukussuku",
		"Kinyomo"=>"Mutima",
		"Kiwere"=>"Sekafu",
		"Kkobe"=>"Kaama",
		"Lugave"=>"Maleere",
		"Mazzi ga Kisasi"=>"Ggongolo",
		"Mbogo"=>"Ndeerwe",
		"Mbwa"=>"Kyuma kya Mbwa",
		"Mmamba"=>"Muguya",
		"Mpeewo"=>"Kayozi",
		"Mpindi"=>"Kiyindiru",
		"Mpologoma"=>"Ngo",
		"Musu"=>"Kayozi",
		"Mutima"=>"Mawuggwe",
		"Nakinsige"=>"Kkunguvvu",
		"Ndiga"=>"Mpologoma",
		"Ndiisa"=>"Namunye",
		"Ngabi"=>"Jjerengesa",
		"Ng'aali"=>"Kasanke akeeru",
		"Ngeye"=>"Kunguvvu",
		"Ngo"=>"Kasimba",
		"Ngonge"=>"Kaneene",
		"Njaza"=>"Ngujulu",
		"Njobe"=>"Bugaala",
		"Njovu"=>"Nvubu",
		"Nkejje"=>"Nkejje Kiyemba",
		"Nkerebwe"=>"Kikirikisi",
		"Nkima"=>"Byenda",
		"Nkula"=>"",
		"Nnamung'oona"=>"Mutima",
		"Nnyonyi Nnyange"=>"Kkunguvvu",
		"Nseenene"=>"Nabangogoma",
		"Nsuma"=>"Kasulubbana",
		"Nswaswa"=>"Goonya",
		"Ntalaganya"=>"Maleere",
		"Nte"=>"Ng'aali",
		"Nvubu"=>"Njovu",
		"Nvuma"=>"Katinvuma",
		"Kasanke"=>"",
		"Kibuba"=>"",
		"Lukato"=>"Kabbokasa",
		"Mbuzi"=>"",
		"Nkebuka"=>"",
		"Nsunu"=>""
	];
}

function omukulu()
{
	return [
		"Abalangira"=>"Ssaabataka",
		"Babiito-Kooki"=>"Ssaababiito",
		"Babiito-Kiziba"=>"Lutayinzibwa",
		"Babiito-Kibulala"=>"Kitahimbwa",
		"Butiko"=>"Ggunju",
		"Ffumbe"=>"Walusimbi",
		"Kasimba"=>"Kabazzi",
		"Kayozi"=>"Kafumu",
		"Kibe"=>"Muyige",
		"Kinyomo"=>"Nakigoye",
		"Kiwere"=>"Luwonko",
		"Kkobe"=>"Namwama",
		"Lugave"=>"Ndugwa",
		"Mazzi ga Kisasi"=>"Ggongolo",
		"Mbogo"=>"Kayiira Gaajuule",
		"Mbwa"=>"Mutasingwa",
		"Mmamba"=>"Gabunga",
		"Mpeewo"=>"Kiggye",
		"Mpindi"=>"Mazige",
		"Mpologoma"=>"Namuguzi",
		"Musu"=>"Muyingo",
		"Mutima"=>"Kakeeto",
		"Nakinsige"=>"Kyeyune",
		"Ndiga"=>"	Lwomwa ",
		"Ndiisa"=>"Mulindwa",
		"Ngabi"=>"Nsamba Lukonge",
		"Ng'aali"=>"Mawesano",
		"Ngeye"=>"Kasujja",
		"Ngo"=>"Muteesasira",
		"Ngonge"=>"Kisolo",
		"Njaza"=>"Kitanda",
		"Njobe"=>"Kiyise",
		"Njovu"=>"Mukalo",
		"Nkejje"=>"Kikwata",
		"Nkerebwe"=>"Kidimbo",
		"Nkima"=>"Mugema",
		"Nkula"=>"Muwangi",
		"Nnamung'oona"=>"Kajjabuwongwa",
		"Nnyonyi Nnyange"=>"Kakoto-Mbaziira",
		"Nseenene"=>"Mugalula",
		"Nsuma"=>"Kibondwe",
		"Nswaswa"=>"Mayengo",
		"Ntalaganya"=>"Bbambaga",
		"Nte"=>"Katongole",
		"Nvubu"=>"Kayita",
		"Nvuma"=>"Kyaddondo",
		"Kasanke"=>"Kyanku",
		"Kibuba"=>"	Nnyanja",
		"Lukato"=>"Magunda/Lyongera",
		"Mbuzi"=>"Kisunsu",
		"Nkebuka"=>"Kayizzi ",
		"Nsunu"=>"Kabugira"
	];
}

function ensibuko()
{
	return [
		"Abalangira"=>"Kaliiti, Busiro",
		"Babiito-Kooki"=>"Rakai, Kkooki",
		"Babiito-Kiziba"=>"Ssanje, Buddu",
		"Babiito-Kibulala"=>"Kibulala, Ssingo",
		"Butiko"=>"Bukalango, Busiro",
		"Ffumbe"=>"Bakka, Busiro",
		"Kasimba"=>"Kyango, Mawokota",
		"Kayozi"=>"Kyango, Mawokota",
		"Kibe"=>"Buluutwe, Kyaggwe ",
		"Kinyomo"=>"Kyasa, Buddu ",
		"Kiwere"=>"Kitanda, Bugangazzi",
		"Kkobe"=>"Buwama, Mawokota",
		"Lugave"=>"Katende, Mawokota",
		"Mazzi ga Kisasi"=>"Kasaka, Buddu",
		"Mbogo"=>"Mugulu, Ssingo",
		"Mbwa"=>"Kiggwa, Busujju",
		"Mmamba"=>"Ssagala, Busiro",
		"Mpeewo"=>"Kkungu, Kyaddondo",
		"Mpindi"=>"Muyenje, Busiro ",
		"Mpologoma"=>"Kasagga, Bulemeezi",
		"Musu"=>"Ssama, Mawokota",
		"Mutima"=>"Bbaale, Buddu",
		"Nakinsige"=>"Mirembe, Kyaggwe",
		"Ndiga"=>"Mbaale, Mawokota",
		"Ndiisa"=>"Mukungwe, Buddu",
		"Ngabi"=>"Buwanda, Mawokota",
		"Ng'aali"=>"Buzooba, Buddu",
		"Ngeye"=>"Busujja, Busiro",
		"Ngo"=>"Bukesa, Butambala",
		"Ngonge"=>"Lweza, Busujju",
		"Njaza"=>"Kirungu, Kyaggwe",
		"Njobe"=>"Mpummudde, Ssingo",
		"Njovu"=>"Kambugu, Busiro",
		"Nkejje"=>"Namukuma,Kyaggwe",
		"Nkerebwe"=>"Budimbo, Ssingo",
		"Nkima"=>"Bbira, Busiro",
		"Nkula"=>"Mayobe, Bugerere",
		"Nnamung'oona"=>"Kyabuwangwa, Ggomba",
		"Nnyonyi Nnyange"=>"Bulimu, Kyaggwe",
		"Nseenene"=>"Kisozi, Ggomba",
		"Nsuma"=>"Bukibondwe, Buvuma",
		"Nswaswa"=>"Bugabo, Buvuma",
		"Ntalaganya"=>"Bbambaga, Bulemeezi",
		"Nte"=>"Mulema, Buddu",
		"Nvubu"=>"Mbazzi, Kyaggwe",
		"Nvuma"=>"Kawempe, Kyaddondo",
		"Kasanke"=>"",
		"Kibuba"=>"",
		"Lukato"=>"Kisuza/Kiziba, Buweekula",
		"Mbuzi"=>"Muwunune",
		"Nkebuka"=>"",
		"Nsunu"=>""
	];
}


function regions()
{
	return [
		"Masekati/central"=>[
			"Busujju"=> ["Bbanda","Butayunja","Kakindu","Maanyi","Malangala"],
			"Busiro"=> ["Bussi","Kakiri","Kakiri Town Council","Kasanje","Katabi","Kiziba(Masuliita)","Mende","Namayumba","Nsangi","Ssisa","Wakiso"],
			"Buruuli"=> ["Buruuli","Kimengo","Miirya","Pakanyi","Nakasongola","Kakooge","Kalongo","Kalungi","Wabinyonyi"],
			"Kabula"=> ["Kabula","Kaliiro","Kasagama","Kinuuka","Lyantonde","Mpumudde"],
			"Bugerere"=> ["Bugerere","Ntenjeru","Nakifuma","Kasawo","Kimenyedde","Nabbale","Nagojje","Namuganga","Ntunda"],
			"Kooki"=> ["Byakabanda","Ddwaniro","Kacheera","Kagamba","Kiziba","Kyalulangira","Lwamaggwa","Lwanda","Rakai","Kakuuto
							","Kasasa","Kibanda","Kifamba","Kyebe"],
			"Kyaddondo"=> ["Gombe","Nabweru","Kampala","Kira","Kyambogo/Busukuma","Makindye","Nabweru","Nangabo","Nansana"],
			"Kyagwe"=> ["Koome Islands","Kyampisi","Mukono","Mpatta","Mpunge","Nakisunga","Nama","Ntenjeru","Nakifuma","Kasawo","Kimenyedde
							","Nabbale","Nagojje","Namuganga","Ntunda"],
			"Ggomba"=> ["Kabulasoke","Maddu","Mpenja","Kanoni","Kyegonza"],
			"Buddu"=> ["Bukomansimbi","Kalungu","Lwengo","Bukakata","Buwunga","Kabonera","Kyanamukaka","Kyesiiga","Mukungwe",
							"Katwe/Butego",	"Kimaanya/Kyabakuza","Nyendo/Senyange","Kabira","Kalisizo","Kasaali","Kirumba","Kyotera","Lwankoni","Nabigasa"],
			"Butambala"=> ["Budde","Bulo","Gombe","Kalamba","Kibibi","Ngando"],
			"Buvuma"=> ["Bugaya","Buvuma","Bweema","Nairambi"],
			"Bulemezi"=> ["Bamunanika","Kalagala","Kamira","Kikyusa","Zirobwe","Bombo","Butuntumula","Katikamu","Luwero","Makulubita","Nyimbwa","Wobulenzi","
								Nakaseke","Kikamulo","Kinyogoga","Kitto","Kiwoko","Ngoma","Semuto","Kapeeka","Kaasangombe","Wakyato","Nakasongola
								","Kakooge","Kalongo","Kalungi","Wabinyonyi"],
			"Buwekula"=> ["Butoloogo","Kitenga","Kiyuni","Madudu","Mubende","Bagezza","Kasambya","Kibalinga","Kigando","Nabingoola"],
			"Mawogola"=> ["Lwemiyaga","Ntuusi","Lugusulu","Lwebitakuli","Mateete","Mijwala","Ssembabule"],
			"Mawokota"=> ["Buwama","Kammengo","Kiringente","Kituntu","Mpigi","Muduma","Nkozi"],
			"Ssese"=> ["Kalangala"],
			"Ssingo"=> ["Kiboga","Bulera","Busimbi","Kalangaalo","Kikandwa","Mityana","Namungo","Ssekanyonyi","Bukuya","Kalwana","Kassanda","Kiganda",
						"Kitumbi","Makokoto","Manyogaseka","Myanzi","Nalutuntu"],
		],
		"Buvaanjuba/East"=> [
			"Bubulo"=> ["Bubutu","Bugobero","Bukhabusi","Bukhaweka","Bukhofu","Bukiabi","Bukoho","Bukusu","Bumbo","Bumwoni","Bunabwana","Bupoto","Busukuya",
							"Butiru","Butta","Buwabwala","Buwagogo","Kaato","Khabutoola","Lwakhakha","Magale","Manafwa","Mukoto","Nalondo","Namabya","Namboko"
							,"Sibanga","Sisuni","Tsekululu","Weswa"],
			"Bujenje"=> ["Budongo","Bwijanga"],
			"Budaka"=> ["Budaka","Budaka Town Council","Kachomo","Kaderuna","Kakule","Lyama","Naboa","Nansanga"],
			"Budama"=> ["Iyolwa","Kirewa","Kisoko","Magola","Mulanda","Nabuyoga","Nagongera","Paya","Petta","Rubongi","Sopsop"],
			"Budiope"=> ["Bugaya","Buyende","Kagulu","Kidera","Nkondo"],
			"Budyebo"=> ["Lwampanga","Nabiswera","Nakitoma","Rwabyata"],
			"Bugembe"=> ["Bugembe  T.C", "Mafubira" ,"Kakira", "Busedde"],
			"Bugabula"=> ["Balawoli","Bulopa","Butansi","Kamuli","Kitayunjwa","Nabwigulu","Namasagali","Namwendwa"],
			"Bukooli"=> ["Banda","Buhemba","Buswale","Buyinja","Mutumba","Namayingo","Sigulu"],
			"Bukooli"=> ["Budhaya","Bugiri Town Council","Bulesa","Bulidha","Buluguyi","Buwunga","Iwemba","Kapyanga","Muterere","Nabukalu","Nankoma"],
			"Buikwe"=> ["Buikwe","Buikwe Town Council","Kawolo","Lugazi Town Council","Najja","Najjembe","Ngogwe","Njeru Town Council",
							"Nkokonjeru Town","Nyenga","Ssi","Wakisi"],
			"Bugweri"=> ["Busembatia","Buyanga","Iganga","Ibulanku","Igombe","Makuutu","Namalemba"],
			"Bukedia"=> ["Bukedea","Bukedea Town Council","Kachumbala","Kidongole","Kolir","Malera"],
			"Bulambuli"=> ["Buginyanya","Bukhalu","Bulago","Bulegeni","Bulegeni Town Council","Buluganya","Bumasobo","Bunambutye","Bwikhonge",
								"Lusha","Masira","Muyembe","Muyembe Town Council","Nabbongo","Namisuni","Simu","Sisiyi"],
			"Bulamoji"=> ["Bumanya","Gadumire","Kaliro","Namugongo","Namwiwa","Nawaikoke"],
			"Busia"=> ["Eastern Division - Busia","Western Division - Busia"],
			"Busiki"=> ["Bulange","Ivukula","Kibaale","Magada","Namutumba"."Nsinze"],
			"Bunyole"=> ["Butaleja","Butaleja Town Council","Himutu","Kachonga","Mazimasa","Naweyo","Nawanjofu","Budumba","Busaba","Busabi","Busolwe",
							"Busolwe Town Council"],
			"Bunya"=> ["Baitambogwe","Bukabooli","Bukatube","Busakira","Buwaaya","Imanyiro","Jaguzi","Kigandalo","Kityerera","Malongo",
							"Mayuge","Mpungwe","Wairasa"],
			"Buzaaya"=> ["Bugulumbya","Kisozi","Mbulamuti","Nawanyago","Wankole"],
			"Iki-Iki"=> ["Iki-Iki","Kameruka","Kamonkoli","Katira","Mugiti"],
			"Kaberamaido"=> ["Alwa","Aperikira","Kaberamaido","Kaberamaido","Kobulubulu","Ochero"],
			"Kagoma"=> ["Budondo","Butagaya","Buwenge","Buyengo"],
			"Kigulu"=> ["Bulamagi","Iganga T.C","Nabitende","Nakalama","Nakigo","Nambale","Namungalwe","Nawandala","Nawanyingi"],
			"Jinja"=> ["Jinja Central","Kimaka /Mpumudde","Masese","Walukuba/Masese"],
			"Luuka"=> ["Bukanga","Bukooma","Bulongo","Ikumbya","Irongo","Nawampiti","Waibuga"],
			"Samia-Bugwe"=> ["Buhehe","Bulumbi","Busia T.C","Busime","Busitema","Buteba","Buyanga","Dabani","Lumino","Lunyo","Majanji","Masaba","Masafu",
								"Masinya","Sikuda"],
			"Kongasis"=> ["Bukwa","Bukwo Town Council","Chepkwasta","Chesower","Kabei","Kamet","Kaptererwo","Kortek","Mount Elgon","Riwo",
							"Senendet","Suam","Tulel"],
			"Mbale"=> ["Bbaale","Bungokho","Galiraya","Kayonza - Kayunga","Kitimbwa"],
			"Manjiya"=> ["Bubiita","Bududa","Bududa Town Council","Bukalasi","Bukibokolo","Bukigai","Bulucheke",
							"Bumasheti","Bumayoka","Bushika","Bushiribo","Bushiyi","Buwali","Nabweya,Nakatsi","Nalwanza"],
			"Ntengeru"=> ["Busaana","Kangulumira","Kayunga","Nazigo"],
			"Kibuku"=> ["Bulangira","Buseta","Kabweri","Kadama","Kagumu","Kasasira","Kibuku","Kirika","Tirinyi"],
			"Soroti"=> ["Arapai","Asuret","Gweri","Kamuda","Katine","Soroti","Tubur"],
			"Tororo"=> ["Kwapa","Malaba","Mella","Merikit","Molo","Mukuju","Osukuru"],
		],
		"Bugwaanjuba/West"=> [
			"Bukanga"=> ["Endinzi","Kashumba","Mbaare","Ngarama","Rugaaga","Rushasha"],
			"Banyaruguru"=> ["Katunguru","Kichwamba","Magambo","Rubirizi","Rutoto","Ryeru"],
			"Buhweju"=> ["Bihanga","Bitsya","Burere","Engaju","Karungu","Nsiika Town Council","Nyakishana","Rwengwe"],
			"Bukonzo"=> ["Bwera","Ihandiro","Isango","Karambi","Kisinga","Kitholu","Kyarumba","Kyondo","Mahango","Mpondwe","Munkunyu","Nyakiyumbu"],
			"Buliisa"=> ["Biiso","Buliisa","Buliisa Town Council","Butiaba","Kigwera","Kihungya","Ngwedo"],
			"Bughendera"=> ["Bukonzo","Harugali","Kasitu","Ndugutu","Ngamba","Ntotoro","Sindila"],
			"Budadiri"=> ["Budadiri","Bugitimwa","Buhugu","Bukhulo","Bukiise","Bukiyi","Bukyabo","Bukyambi","Bumalimba","Bumasifwa",
								"Bunyafwa","Busulani","Butandiga","Buteza","Buwalasi","Buwasa","Buyobo","Masaba","Nalusala","Sironko","Zesui"],
			"Bugangaizi"=> ["Kisiita","Mpasaana","Nkooko","Birembo","Bwanswa","Narweyo"],
			"Bushenyi"=> ["Central Division - Bushenyi","Ishaka Division","Nyakabirizi Division"],
			"Bwamba"=> ["Bubandi","Bubukwanga","Bundibugyo Town Council","Busaru","Kirumya","Kisubba","Mirambi","Nyahuka  Town Council"],
			"Igara"=> ["BitoomaBumbaire","Ibaare","Kakanju","Kyabugimbi","Kyamuhunga","Kyeizoba","Nyabubare","Ruhumuro"],
			"Bugahya"=> ["Buhanika","Buseruka","Kigorobya","Kitoba","Kyabigambire"],
			"Buhaguzi"=> ["Bugambe","Buhimba","Kabwoya","Kiziranfumbi","Kyangwali"],
			"Buhanga"=> ["Endinzi","Kashumba","Mbaare","Ngarama","Rugaaga","Rushasha"],
			"Bunyangabu"=> ["Buheesi","Kabonero","Kateebwa","Kibiito","Kibiito","Kisomoro","Rubona","Rwimi"],
			"Buyaga"=> ["Kabamba","Kagadi","Kiryanga","Kyanaisoke","Kyenzige","Mabaale","Pachwa","Burora","Bwikara","Kyakabadiima",
							"Kyaterekera","Mpeefu","Muhorro","Ndaiga","Rugashari","Ruteete - Kibaale"],
			"Burahya"=> ["Bukuuku","Busoro","Hakibale","Karambi","Karangura","Kasenda","Kicwamba","Kijura","Mugusu","Ruteete","Kabarole"],
			"Bufumbira"=> ["Bufumbira","Bukimbiri","Busanza","Chahi","Kanaba","Kirundo","Kisoro","Muramba","Murora","Nyabwishenya","Nyakabande","Nyakinama
								","Nyarubuye","Nyarusiza","Nyundo"],
			"Busongora"=> ["Bugoye","Buhuhira","Bwesumbu","Hima","Karusandara","Kasese T.C","Kichwamba","Kilembe","Kitswamba"
								,"Kyabarungira","Kabatoro","Lake Katwe","Maliba","Muhokya","Rukoki"],
			"Buyanja"=> ["Bubango","Bwamiramira","Kibaale","Kyebando","Matale","Mugarama","Nyamarunda","Nyamarwa"],
			"Hoima"=> ["Bujumbura","Busiisi","Kahoora","Mparo"],
			"Ibanda"=> ["Bisheshe","Ibanda Town Council","Ishongororo","Kashangura","Keihangara","Kicuzi","Kijongo","Kikyenkye","Nsasi",
							"Nyabuhikye","Nyamarebe","Rukiri","Rushango"],
			"Kashari"=> ["Biharwe","Bubaare","Bukiiro","Kagongi","Kakiika","Kashare","Rubaya","Rubindi","Rugaaga","Rwanyamahembe"],
			"Kajara"=> ["Bwongera","Ihunga","Kibatsi","Nyabihoko"],
			"Katerera"=> ["Katanda","Katerera","Kirugu","Kyabakara"],
			"Kazo"=> ["Buremba","Burunga","Engari","Kanoni","Kazo","Nkungu","Rwemikoma"],
			"Isingiro"=> ["Birere","Isingiro","Kaberebere",",Kabingo","Kabuyanda","Kikagate","Masha","Nyakitunda","Nyamuyanja","Ruborogota"],
			"Fort Portal"=> ["Kabarole"],
			"Ndorwa"=> ["Buhara","Butanda","Kaharo","Kamuganguzi","Katuna","Kitumba","Kyanamira","Maziba","Rubaya"],
			"Kabaale"=> ["Kabale Central","Kabale Northern","Kabale Southern"],
			"Kaseese"=> ["Bulembia","Kasese","Nyamwamba"],
			"Kibaale"=> ["Biguli","Busiriba","Bwizi","Kabambiro","Kahunge","Kamwenge","Nkoma"],
			"Kitagwenda"=> ["Buhanda","Kanara - Kamwenge","Kicheche","Mahyoro","Ntara","Nyabbani"],
			"Kinkizi"=> ["Kambuga","Kanungu","Kanyantorogo","Kayonza","Kihiihi","Kirima","Mpungu","Nyamirama","Rugyeyo","Rutenga"],
			"Kyaka"=> ["Hapuuyo","Kakabara","Kasule","Kyegegwa","Mpara","Ruyonza","Rwentuha"],
			"Masindi"=> ["Masindi","Karujubu","Kigulya","Nyangahya"],
			"mwenge"=> ["Bufunjo","Bugaaki","Butiiti","Butunduzi","Katooke","Kigaraale","Kihuura","Kisojo","Kyarusozi"
								,"Kyenjojo","Nyabuharwa","Nyankwanzi","Nyantungo"],
			"Ntoroko"=> ["Butungama","Bweramule","Kanara","Karugutu","Kibuuku","Nombe","Rwebisengo"],
			"Nyabusozi"=> ["Kanyaryeru","Kashongi","Kenshunga","Kikatsi","Kinoni","Kiruhura","Kitura","Nyakashashara","Sanga"],
			"Rubanda"=> ["Bubare","Bufundi","Hamurwa","Ikumba","Muko","Nyamweeru","Ruhija"],
			"Rubabo"=> ["Buyanja","Kebisoni","Nyakishenyi","Nyarushanje"],
			"Rujumbura"=> ["Bugangari","Buhunga","Bwambara","Kagunga","Nyakagyeme","Ruhinda","Rukungiri"],
			"Rukiga"=> ["Bukinda","Kamwezi","Kashambya","Muhanga","Rwamucucu"],
			"Mbarara"=> ["Kakoba","Kamukuzi","Nyamitanga"],
			"Rwampara"=> ["Bugamba","Mwizi","Ndeija","Nyakayojo","Rugando"],
			"Ruhaama"=> ["Itojo","Ntungamo","Nyakyera","Ruhaama","Rukoni","Rweikiniro"],
			"Ruhinda"=> ["Bitereko","Kabira","Kanyabwanga","Kashenshero","Kashenshero","Katenga","Kiyanga","Mayanga","Mitooma","Mutara","Rurehe"],
			"Rushenyi"=> ["Kayonza","Ngoma","Rubaare","Rugarama"],
			"Serere"=> ["Atiira","Kateta","Kyere","Serere/Olio"],
			"Sheema"=> ["Bugongi","Bugongi Town Council","Kabwohe/Itendero Town","Kagango","Kasaana","Kibingo","Kigarama","Kitagata"
						,"Kyangyenyi","Rugarama","Shuuku"],
		],
		"Mambuka/North"=> [
			"Agago"=> ["Adilang","Arum","Kalongo Town Council","Kotomor","Lamiyo","Lapono","Lira-Palwo","Lokole","Lokole Town Council",
							"Omiya Pacwa","Omot","Paimol","Parabongo","Patongo","Patongo Town Council","Wol"],
			"Aguri"=> ["Abako","Amugu","Awei","Omoro"],
			"Agule"=> ["Agule","Akisim","Apopong","Chelekura","Gogonyo","Kameke"],
			"Arua"=> ["Arua Hill","Oli River"],
			"Aruu"=> ["Acholi","Angagura","Atanga","Awere","Laguti","Lapul","Latanya","Ogom","Pader","Pajule","Puranga"],
			"Amuria"=> ["Abarilela","Amuria Town Council","Asamuk","Kuju","Morungatuny","Orungo","Wera"],
			"Aringa"=> ["Apo","Ariwa","Drajini/Arajim","Kei","Kerwa","Kochi","Kululu","Kuru","Lodonga","Midigo","Odravu","Romogi","Yumbe "],
			"Ayivu"=> ["Adumi,Aroi","Ayivuni","Dadamu","Manibe","Oluko","Pajulu"],
			"Buruli"=> ["Kimengo","Miirya","Pakanyi"],
			"East Moyo"=> ["Adjumani Town Council","Adropi","Arinyapi","Ciforo","Dzaipi","Itirikwa","Ofua","Pachara","Pakele","Ukusijoni"],
			"Bokora"=> ["Iriiri","Lokopo","Lopei","Lorengecora","Lotome","Matany","Napak"],
			"Butebo"=> ["Butebo","Kabwangasi","Kakoro","Kanginima","Kibale","Opwateta","Petete"],
			"Dokolo"=> ["Adekinino","Adok","Agwatta","Amwoma","Batta","Dokolo","Kangai","Okwalongwen","Okwongodul"],
			"Chekwii"=> ["Kakomongole","Loregae","Moruita","Nakapiripirit","Namalu"],
			"Chua"=> ["Akwang","Kitgum Matidi","Amida","Layamo","Lagoro","Muchwini","Nam-Okora","Omiya-Anyima","Orom"],

			"Doroth"=> ["Kaabong","Kalapata","Kamion","Kathile","Lodiko","Lolelia","Loyoro","Sidok (Kapoth)","Kapedo","Karenga(Napore)",
							"Kawalakol","Lobalangit"],
			"Jonam"=> ["Alwi","Pakwach","Panyango","Panyimur","Wadelai"],
			"Erute"=> ["Adekokwok","Agali","Agweng","Amach","Aromo","Barr","Lira","Ngetta","Ogur"],
			"Gulu"=> ["Bar-Dege","Laroo","Layibi","Pece"],
			"Jie"=> ["Kacheri","Kotido","Nakapelimoru","Panyangara","Rengen"],
			"Kalaki"=> ["Anyara","Apapai","Bululu","Kakure","Kalaki","Otuboi"],
			"Kasilo"=> ["Bugondo","Kadungulu","Labor","Pingire"],
			"Kapelebyong"=> ["Acowa","Kapelebyong","Obalanga"],
			"Tingey"=> ["Chema","Gamogo","Kabeywa","Kapchesombe","Kapchorwa","Kapsinda","Kaptanya","Kapteret","Kaserem","Kawowo","Munarya",
								"Sipi","Tegeres"],
			"Kinanda"=> ["Bweyale","Kigumba","Kiryandongo","Masindi Port","Mutunda"],
			"Kilak"=> ["Amuru","Amuru Town Council","Atiak","Lamogi","Pabbo"],
			"Kioga"=> ["Agikdak","Agwingiri","Akwon","Amolatar Town Council","Aputi","Arwotcek","Awello","Etam","Muntu","Namasale"],
			"Koboko"=> ["Abuku","Dranya","Koboko","Kuluba","Lobule","Ludara","Midia"],
			"Kole"=> ["Aboke","Akalo","Alito","Ayer","Balla","Kole"],
			"Kumi"=> ["Atutur","Kanyum","Kumi","Mukongoro","Nyero","Ongino"],
			"Kwania"=> ["Abongomola","Aduku","Aduku Town Council","Cawente","Inomo","Nambieso"],
			"Kween"=> ["Benet","Binyinyi",",Greek River","Kaproron","Kaptum","Kitawoi","Kwanyiy","Kwosir","Moyok","Ngenge"],
			"Labwor"=> ["ABIM","ABIM TOWN COUNCIL","ALEREK","LOTUKEI","MORULEM","NYAKWAE"],
			"Lamwo"=> ["Agoro","Lokung","Madi-Opei","Ogili","Padibe","Palabek-Gem","Palabek-Kal","Paloga"],
			"Madi-Okollo"=> ["Anyiribu","Ewanga","Offaka","Ogoko","Okollo","Pawor","Rhino Camp","Rigbo","Uleppi"],
			"Maruzi"=> ["Akokoro","Apac","Apac Town Council","Chegere","Ibuje"],
			"Maracha"=> ["Kijomoro","Maracha","Nyadri","Oleba","Olufe","Oluvu","Tara","Yivu"],
			"Mathemiko"=> ["Katikekile","Moroto","Nadunget","Rupa","Tapac"],
			"Moroto"=> ["Abia","Akura","Alebtong","Aloi","Apala"],
			"Ngora"=> ["Kapir","Kobwin","Mukura","Ngora"],
			"Nwoya"=> ["Alero","Anaka","Koch-Goma","Purongo"],
			"Obongi"=> ["Aliba","Gimara","Itula","Dufile","Laropi","Lefori","Metu","Moyo"],
			"Okolo"=> ["Abanga","Atyak","Jangokoro","Kango","Nyapea","Paidha","Warr","Zeu","Zombo"],
			"Omoro"=> ["Bobi","Koro","Lakwana","Lalogi","Odek","Ongako"],
			"Otuke"=> ["Adwari","Ogor","Okwang","Olilim","Orum","Otuke"],
			"Oyam"=> ["Aber","Abok","Achaba","Aleka","Icheme","Kamdini","Loro","Minakulu","Myene","Ngai","Otwal","Oyam"],
			"Padyere"=> ["Akworo","Atego","Erussi","Kucwiny","Ndhew","Nebbi","Nyaravur","Parombo"],
			"Pian"=> ["Lolachat","Lorengedwat","Nabilatuk"],
			"Palisa"=> ["Kamuge","Kasodo","Olok","Pallisa","Puti-Puti"],
			"Terego"=> ["Aii-Vu/Ajivu","Beleafe","Katrini","Odupi","Omugo","Uriama"],
			"Upe"=> ["Amudat","Amudat Town Council","Karita","Loroo"],
			"Usuk"=> ["Katakwi","Ngariam","Obalanga","Ongongoja","Palam","Usuk"],
			"Vurra"=> ["Ajia","Arivu","Logiri","Vurra"],
			"Aswa"=> ["Awach","Bungatira","Paicho","Palaro","Patiko","Unyama"],
			"Toroma"=> ["Kapujan","Magoro","Omodoi","Toroma"],	
		],
		"Not Ugandan/Simunayuganda"=> [
			"Origin"=> ["African","Asian","European","American"]
		]
	];
}